### ISSUE TITLE
How do you generate the certificate ?

### ISSUE THREAD

**Issue by Cyrille37** [jaysee/ovh-cdn-ssl-renew#1]
Hello,
I don't understand howto use of this tool, because before uploading the certificate, you have to generate/renew it. And to generate/renew certificate on the backend you have to disable the CDN, to let LetsEncrypt directly speak to the backend (auth check), isn't it ?
Thanks.

**Comment by jaysee** [comment]
You have to renew/generate the certificats the "normal" way, then this script uploads the renewed/generated cert to OVH CDN.

And Yes, the only way I found for generating/renewing cert is to disable CDN during the process, else, certbots will query the CDN and get a bad answer! 
I tried to use some rules to exclude .well-known folder from CDN, but never succeed ;(

**Comment by Cyrille37** [comment]
Thanks a lot for your answer ! :-)
How long do you wait after CDN disabled and before starting renew process (DNS propagation) ?

**Comment by jaysee** [comment]
I don't really wait for DNS propagation, OVH DNS reflects instantly the CDN changes, and letsencrypt ask directlty to the domain DNS bypassing any cache, so it works without any waiting.

BTW I made another (yet unpublished) script to enable/disable CDN easily...

**Comment by Cyrille37** [comment]
Thanks a lot !
Cheers
